version: '3.7'

services:
  database:
    image: postgres:latest
    restart: always
    container_name: pg-database
    ports: 
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./.docker/init.sh:/docker-entrypoint-initdb.d/init.sh
  api:
    image: node:16
    container_name: appraisal-api
    restart: always
    depends_on:
      - database
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./:/usr/app
    working_dir: /usr/app
    command: >
      bash -c "npm i --production && npm run build && npm start"
    logging:
      driver: "json-file"
      options: 
        max-size: "2m"
        max-file: "2"

      
    